/*
Copyright 2025 OpzKit

Licensed under the MIT License.
See LICENSE file in the project root for full license information.
*/

package secrets

import "context"

// Backend is the interface for storing/retrieving database credentials
// generated by the operator. Each implementation persists a DatabaseSecret
// to its underlying store (AWS Secrets Manager, a Kubernetes Secret,
// Infisical, …) under a backend-specific name and returns a Locator string
// (ARN, namespace/name, Infisical path, …) used for status reporting and
// downstream consumers.
//
// Implementations must be safe for concurrent use by multiple goroutines.
type Backend interface {
	// Exists reports whether a secret with the given name is currently stored.
	Exists(ctx context.Context, name string) (bool, error)

	// Get reads back a previously stored DatabaseSecret.
	Get(ctx context.Context, name string) (*DatabaseSecret, error)

	// Create stores a new secret. Returns the backend-specific locator and a
	// version identifier. If the underlying backend has a "scheduled for
	// deletion" or similar soft-deleted state, implementations should restore
	// and update rather than fail. The optional template controls the JSON
	// shape; pass an empty string for the default.
	Create(ctx context.Context, name, description string, secret *DatabaseSecret, tags map[string]string, template string) (locator string, version string, err error)

	// Update overwrites an existing secret. Returns the new version.
	// Returns *SecretNotFoundError if no secret with the name exists.
	// Returns *SecretMarkedForDeletionError if the backend has soft-deleted
	// the secret and it must be restored before update.
	Update(ctx context.Context, name string, secret *DatabaseSecret, template string) (version string, err error)

	// Delete removes the secret. forceDelete bypasses any recovery window
	// the backend supports; backends without such a concept treat both
	// values the same. Deleting a non-existent secret is not an error.
	Delete(ctx context.Context, name string, forceDelete bool) error

	// Locator returns the backend-specific identifier for an existing
	// secret (e.g. an AWS ARN, "namespace/name" for a Kubernetes Secret,
	// or the full Infisical path).
	Locator(ctx context.Context, name string) (string, error)

	// SyncTags applies the given tag set to the secret, removing any tags
	// not present in desired. Backends without tag support no-op.
	SyncTags(ctx context.Context, name string, desired map[string]string) error
}
